import type { CardDefinition } from './types';

const c = (card: CardDefinition): CardDefinition => card;

export const ALL_CARDS: CardDefinition[] = [
  c({
    id: 'brick_patch',
    name: 'Brick Patch',
    domain: 'bricks',
    cost: 3,
    tags: ['defense'],
    text: '+6 Wall',
    effects: [{ type: 'adjustWall', target: 'self', amount: 6 }],
    illustrationKey: 'wall',
  }),
  c({
    id: 'reinforce',
    name: 'Reinforce',
    domain: 'bricks',
    cost: 5,
    tags: ['defense'],
    text: '+4 Wall, +2 Tower',
    effects: [
      { type: 'adjustWall', target: 'self', amount: 4 },
      { type: 'adjustTower', target: 'self', amount: 2 },
    ],
    illustrationKey: 'masonry',
  }),
  c({
    id: 'quarry_team',
    name: 'Quarry Team',
    domain: 'bricks',
    cost: 8,
    tags: ['economy'],
    text: '+1 Quarry',
    effects: [{ type: 'adjustGenerator', target: 'self', generator: 'quarry', amount: 1 }],
    illustrationKey: 'quarry',
  }),
  c({
    id: 'bastion',
    name: 'Bastion',
    domain: 'bricks',
    cost: 12,
    tags: ['defense'],
    text: '+12 Wall',
    effects: [{ type: 'adjustWall', target: 'self', amount: 12 }],
  }),
  c({
    id: 'foundation',
    name: 'Foundation',
    domain: 'bricks',
    cost: 10,
    tags: ['defense', 'economy'],
    text: '+8 Tower',
    effects: [{ type: 'adjustTower', target: 'self', amount: 8 }],
  }),
  c({
    id: 'stone_wall',
    name: 'Stone Wall',
    domain: 'bricks',
    cost: 7,
    tags: ['defense'],
    text: '+10 Wall',
    effects: [{ type: 'adjustWall', target: 'self', amount: 10 }],
    illustrationKey: 'wall',
  }),
  c({
    id: 'fortify',
    name: 'Fortify',
    domain: 'bricks',
    cost: 6,
    tags: ['defense'],
    text: '+6 Wall, next dmg -2',
    effects: [
      { type: 'adjustWall', target: 'self', amount: 6 },
      { type: 'setIncomingDamageReduction', amount: 2 },
    ],
  }),
  c({
    id: 'rampart',
    name: 'Rampart',
    domain: 'bricks',
    cost: 9,
    tags: ['defense'],
    text: '+14 Wall',
    effects: [{ type: 'adjustWall', target: 'self', amount: 14 }],
  }),
  c({
    id: 'mason',
    name: 'Mason',
    domain: 'bricks',
    cost: 4,
    tags: ['economy', 'defense'],
    text: '+1 Quarry, +2 Wall',
    effects: [
      { type: 'adjustGenerator', target: 'self', generator: 'quarry', amount: 1 },
      { type: 'adjustWall', target: 'self', amount: 2 },
    ],
  }),
  c({
    id: 'repair',
    name: 'Repair',
    domain: 'bricks',
    cost: 4,
    tags: ['defense'],
    text: '+5 Tower',
    effects: [{ type: 'adjustTower', target: 'self', amount: 5 }],
    illustrationKey: 'tower',
  }),
  c({
    id: 'double_wall',
    name: 'Double Wall',
    domain: 'bricks',
    cost: 8,
    tags: ['defense'],
    text: 'Wall x2 (cap 30)',
    effects: [{ type: 'doubleWall', cap: 30 }],
  }),
  c({
    id: 'tower_boost',
    name: 'Tower Boost',
    domain: 'bricks',
    cost: 9,
    tags: ['economy', 'defense'],
    text: '+10 Tower',
    effects: [{ type: 'adjustTower', target: 'self', amount: 10 }],
    illustrationKey: 'tower',
  }),
  c({
    id: 'brick_flow',
    name: 'Brick Flow',
    domain: 'bricks',
    cost: 5,
    tags: ['economy'],
    text: '+8 Bricks',
    effects: [{ type: 'adjustResource', target: 'self', resource: 'bricks', amount: 8 }],
    illustrationKey: 'crate',
  }),
  c({
    id: 'construction',
    name: 'Construction',
    domain: 'bricks',
    cost: 6,
    tags: ['economy'],
    text: '+2 Tower per Quarry',
    effects: [{ type: 'towerPerGenerator', generator: 'quarry', amountPer: 2 }],
    illustrationKey: 'tower',
  }),
  c({
    id: 'barrier',
    name: 'Barrier',
    domain: 'bricks',
    cost: 5,
    tags: ['defense'],
    text: 'Prevent next 5 dmg',
    effects: [{ type: 'setBarrier', amount: 5 }],
  }),
  c({
    id: 'wall_shift',
    name: 'Wall Shift',
    domain: 'bricks',
    cost: 4,
    tags: ['control'],
    text: 'Convert 6 Wall -> 6 Tower',
    effects: [{ type: 'wallToTower', amount: 6 }],
  }),
  c({
    id: 'solidify',
    name: 'Solidify',
    domain: 'bricks',
    cost: 7,
    tags: ['defense', 'control'],
    text: '+8 Wall, enemy -2 dmg next turn',
    effects: [
      { type: 'adjustWall', target: 'self', amount: 8 },
      { type: 'setOutgoingDamagePenalty', target: 'opponent', amount: 2, turns: 1 },
    ],
  }),
  c({
    id: 'heavy_stones',
    name: 'Heavy Stones',
    domain: 'bricks',
    cost: 11,
    tags: ['defense'],
    text: '+16 Wall',
    effects: [{ type: 'adjustWall', target: 'self', amount: 16 }],
  }),
  c({
    id: 'fortress',
    name: 'Fortress',
    domain: 'bricks',
    cost: 15,
    tags: ['defense', 'finisher'],
    text: '+20 Wall',
    effects: [{ type: 'adjustWall', target: 'self', amount: 20 }],
  }),
  c({
    id: 'architect',
    name: 'Architect',
    domain: 'bricks',
    cost: 12,
    tags: ['economy', 'defense'],
    text: '+1 Quarry, +6 Tower',
    effects: [
      { type: 'adjustGenerator', target: 'self', generator: 'quarry', amount: 1 },
      { type: 'adjustTower', target: 'self', amount: 6 },
    ],
  }),

  c({
    id: 'strike',
    name: 'Strike',
    domain: 'weapons',
    cost: 3,
    tags: ['attack'],
    text: '4 dmg',
    effects: [{ type: 'attack', amount: 4, source: 'attack' }],
    illustrationKey: 'sword',
  }),
  c({
    id: 'slash',
    name: 'Slash',
    domain: 'weapons',
    cost: 4,
    tags: ['attack'],
    text: '5 dmg',
    effects: [{ type: 'attack', amount: 5, source: 'attack' }],
    illustrationKey: 'crossed_swords',
  }),
  c({
    id: 'raid',
    name: 'Raid',
    domain: 'weapons',
    cost: 6,
    tags: ['attack'],
    text: '7 dmg',
    effects: [{ type: 'attack', amount: 7, source: 'attack' }],
    illustrationKey: 'crossed_swords',
  }),
  c({
    id: 'catapult',
    name: 'Catapult',
    domain: 'weapons',
    cost: 13,
    tags: ['attack', 'finisher'],
    text: '10 dmg',
    effects: [{ type: 'attack', amount: 10, source: 'attack' }],
  }),
  c({
    id: 'breach',
    name: 'Breach',
    domain: 'weapons',
    cost: 6,
    tags: ['attack', 'sabotage'],
    text: '8 Wall dmg',
    effects: [{ type: 'attack', amount: 8, wallOnly: true, source: 'attack' }],
    illustrationKey: 'ram',
  }),
  c({
    id: 'smash',
    name: 'Smash',
    domain: 'weapons',
    cost: 5,
    tags: ['attack'],
    text: '6 dmg',
    effects: [{ type: 'attack', amount: 6, source: 'attack' }],
    illustrationKey: 'sword',
  }),
  c({
    id: 'heavy_blow',
    name: 'Heavy Blow',
    domain: 'weapons',
    cost: 9,
    tags: ['attack'],
    text: '12 dmg',
    effects: [{ type: 'attack', amount: 12, source: 'attack' }],
  }),
  c({
    id: 'berserk',
    name: 'Berserk',
    domain: 'weapons',
    cost: 7,
    tags: ['attack'],
    text: '9 dmg, self -3 Tower',
    effects: [
      { type: 'attack', amount: 9, source: 'attack' },
      { type: 'adjustTower', target: 'self', amount: -3 },
    ],
  }),
  c({
    id: 'sabotage',
    name: 'Sabotage',
    domain: 'weapons',
    cost: 9,
    tags: ['sabotage'],
    text: 'Enemy -1 Quarry/Barracks',
    effects: [{ type: 'sabotageGenerators' }],
  }),
  c({
    id: 'siege_crew',
    name: 'Siege Crew',
    domain: 'weapons',
    cost: 8,
    tags: ['economy'],
    text: '+1 Barracks',
    effects: [{ type: 'adjustGenerator', target: 'self', generator: 'barracks', amount: 1 }],
    illustrationKey: 'drum',
  }),
  c({
    id: 'double_strike',
    name: 'Double Strike',
    domain: 'weapons',
    cost: 8,
    tags: ['attack'],
    text: '2x5 dmg',
    effects: [{ type: 'attack', amount: 5, hits: 2, source: 'attack' }],
  }),
  c({
    id: 'pierce',
    name: 'Pierce',
    domain: 'weapons',
    cost: 7,
    tags: ['attack', 'control'],
    text: '6 dmg bypass Wall',
    effects: [{ type: 'attack', amount: 6, bypassWall: true, source: 'attack' }],
  }),
  c({
    id: 'destroy_wall',
    name: 'Destroy Wall',
    domain: 'weapons',
    cost: 10,
    tags: ['sabotage'],
    text: '-12 Wall',
    effects: [{ type: 'attack', amount: 12, wallOnly: true, source: 'attack' }],
  }),
  c({
    id: 'pressure',
    name: 'Pressure',
    domain: 'weapons',
    cost: 6,
    tags: ['attack', 'sabotage'],
    text: 'Enemy -4 Wall, -2 Tower',
    effects: [
      { type: 'adjustWall', target: 'opponent', amount: -4 },
      { type: 'adjustTower', target: 'opponent', amount: -2 },
    ],
    illustrationKey: 'cracked_shield',
  }),
  c({
    id: 'war_cry',
    name: 'War Cry',
    domain: 'weapons',
    cost: 5,
    tags: ['control'],
    text: 'Next attack +4',
    effects: [{ type: 'setNextAttackBonus', amount: 4 }],
  }),
  c({
    id: 'overrun',
    name: 'Overrun',
    domain: 'weapons',
    cost: 11,
    tags: ['attack', 'finisher'],
    text: '14 dmg',
    effects: [{ type: 'attack', amount: 14, source: 'attack' }],
    illustrationKey: 'crossed_swords',
  }),
  c({
    id: 'harass',
    name: 'Harass',
    domain: 'weapons',
    cost: 4,
    tags: ['sabotage'],
    text: 'Enemy -2 random resource',
    effects: [{ type: 'adjustRandomResource', target: 'opponent', amount: -2 }],
  }),
  c({
    id: 'pillage',
    name: 'Pillage',
    domain: 'weapons',
    cost: 8,
    tags: ['sabotage', 'economy'],
    text: 'Steal 5 resources',
    effects: [{ type: 'stealResources', amount: 5 }],
  }),
  c({
    id: 'bombard',
    name: 'Bombard',
    domain: 'weapons',
    cost: 12,
    tags: ['attack', 'sabotage'],
    text: '8 dmg + destroy 6 Wall',
    effects: [
      { type: 'attack', amount: 8, source: 'attack' },
      { type: 'attack', amount: 6, wallOnly: true, source: 'attack' },
    ],
  }),
  c({
    id: 'army',
    name: 'Army',
    domain: 'weapons',
    cost: 15,
    tags: ['attack', 'economy', 'finisher'],
    text: '+2 Barracks, 6 dmg',
    effects: [
      { type: 'adjustGenerator', target: 'self', generator: 'barracks', amount: 2 },
      { type: 'attack', amount: 6, source: 'attack' },
    ],
  }),

  c({
    id: 'spark',
    name: 'Spark',
    domain: 'crystals',
    cost: 3,
    tags: ['attack'],
    text: '3 Tower dmg',
    effects: [{ type: 'attack', amount: 3, bypassWall: true, source: 'spell' }],
    illustrationKey: 'crystal',
  }),
  c({
    id: 'zap',
    name: 'Zap',
    domain: 'crystals',
    cost: 4,
    tags: ['attack'],
    text: '4 dmg bypass Wall',
    effects: [{ type: 'attack', amount: 4, bypassWall: true, source: 'spell' }],
    illustrationKey: 'crystal',
  }),
  c({
    id: 'arcane_study',
    name: 'Arcane Study',
    domain: 'crystals',
    cost: 8,
    tags: ['economy'],
    text: '+1 Magic',
    effects: [{ type: 'adjustGenerator', target: 'self', generator: 'magic', amount: 1 }],
    illustrationKey: 'book',
  }),
  c({
    id: 'transmute',
    name: 'Transmute',
    domain: 'crystals',
    cost: 4,
    tags: ['control', 'economy'],
    text: 'Convert 6 resources',
    effects: [{ type: 'convertResources', amount: 6 }],
  }),
  c({
    id: 'theft',
    name: 'Theft',
    domain: 'crystals',
    cost: 7,
    tags: ['sabotage', 'economy'],
    text: 'Steal 3 random',
    effects: [{ type: 'stealResources', amount: 3 }],
  }),
  c({
    id: 'drain',
    name: 'Drain',
    domain: 'crystals',
    cost: 6,
    tags: ['sabotage'],
    text: 'Enemy -4 resources',
    effects: [{ type: 'drainEnemyResources', amount: 4 }],
  }),
  c({
    id: 'convert',
    name: 'Convert',
    domain: 'crystals',
    cost: 5,
    tags: ['economy'],
    text: 'Gain 5 of chosen type',
    effects: [{ type: 'gainChosenResource', amount: 5 }],
  }),
  c({
    id: 'crystal_boost',
    name: 'Crystal Boost',
    domain: 'crystals',
    cost: 6,
    tags: ['economy'],
    text: '+8 Crystals',
    effects: [{ type: 'adjustResource', target: 'self', resource: 'crystals', amount: 8 }],
    illustrationKey: 'orb',
  }),
  c({
    id: 'chaos',
    name: 'Chaos',
    domain: 'crystals',
    cost: 10,
    tags: ['control', 'attack'],
    text: 'Random effect (6-12 dmg or +10)',
    effects: [{ type: 'chaos' }],
  }),
  c({
    id: 'mirror',
    name: 'Mirror',
    domain: 'crystals',
    cost: 9,
    tags: ['control'],
    text: 'Repeat last card effect',
    effects: [{ type: 'repeatLastResolved' }],
  }),
  c({
    id: 'freeze',
    name: 'Freeze',
    domain: 'crystals',
    cost: 7,
    tags: ['control', 'sabotage'],
    text: 'Enemy skips gain next turn',
    effects: [{ type: 'setSkipGain', target: 'opponent', turns: 1 }],
  }),
  c({
    id: 'insight',
    name: 'Insight',
    domain: 'crystals',
    cost: 5,
    tags: ['cycle'],
    text: 'Draw 2, discard 1',
    effects: [
      { type: 'drawCards', target: 'self', amount: 2 },
      { type: 'discardCards', target: 'self', amount: 1 },
    ],
  }),
  c({
    id: 'mana_surge',
    name: 'Mana Surge',
    domain: 'crystals',
    cost: 9,
    tags: ['economy'],
    text: '+2 Magic',
    effects: [{ type: 'adjustGenerator', target: 'self', generator: 'magic', amount: 2 }],
    illustrationKey: 'orb',
  }),
  c({
    id: 'hex',
    name: 'Hex',
    domain: 'crystals',
    cost: 8,
    tags: ['sabotage'],
    text: 'Enemy -1 all generators',
    effects: [{ type: 'adjustAllGenerators', target: 'opponent', amount: -1 }],
  }),
  c({
    id: 'curse',
    name: 'Curse',
    domain: 'crystals',
    cost: 6,
    tags: ['control', 'sabotage'],
    text: 'Enemy loses 2 Tower/turn (2 turns)',
    effects: [{ type: 'setCurse', target: 'opponent', turns: 2, towerLoss: 2 }],
  }),
  c({
    id: 'shield',
    name: 'Shield',
    domain: 'crystals',
    cost: 5,
    tags: ['defense', 'control'],
    text: 'Prevent next attack',
    effects: [{ type: 'setShield' }],
    illustrationKey: 'shield',
  }),
  c({
    id: 'flux',
    name: 'Flux',
    domain: 'crystals',
    cost: 7,
    tags: ['control'],
    text: 'Swap resources with enemy',
    effects: [{ type: 'swapResources' }],
  }),
  c({
    id: 'arcane_blast',
    name: 'Arcane Blast',
    domain: 'crystals',
    cost: 11,
    tags: ['attack'],
    text: '9 dmg bypass Wall',
    effects: [{ type: 'attack', amount: 9, bypassWall: true, source: 'spell' }],
    illustrationKey: 'blast',
  }),
  c({
    id: 'control',
    name: 'Control',
    domain: 'crystals',
    cost: 10,
    tags: ['control', 'sabotage'],
    text: 'Enemy discards 2',
    effects: [{ type: 'enemyDiscard', amount: 2 }],
  }),
  c({
    id: 'cataclysm',
    name: 'Cataclysm',
    domain: 'crystals',
    cost: 15,
    tags: ['attack', 'finisher'],
    text: '15 dmg, self -5 Tower',
    effects: [
      { type: 'attack', amount: 15, source: 'spell' },
      { type: 'adjustTower', target: 'self', amount: -5 },
    ],
  }),
];

if (ALL_CARDS.length !== 60) {
  throw new Error(`Expected 60 cards, got ${ALL_CARDS.length}`);
}

export const CARD_BY_ID: Record<string, CardDefinition> = Object.fromEntries(
  ALL_CARDS.map((card) => [card.id, card]),
);

export const ALL_CARD_IDS: string[] = ALL_CARDS.map((card) => card.id);

export const STARTER_DECK_CARD_IDS: string[] = [
  'brick_patch',
  'brick_patch',
  'repair',
  'repair',
  'reinforce',
  'brick_flow',
  'construction',
  'stone_wall',
  'quarry_team',
  'tower_boost',

  'strike',
  'strike',
  'slash',
  'slash',
  'smash',
  'raid',
  'breach',
  'pressure',
  'siege_crew',
  'overrun',

  'spark',
  'spark',
  'zap',
  'zap',
  'crystal_boost',
  'crystal_boost',
  'shield',
  'arcane_study',
  'mana_surge',
  'arcane_blast',
];

if (STARTER_DECK_CARD_IDS.length !== 30) {
  throw new Error(`Expected 30 starter deck cards, got ${STARTER_DECK_CARD_IDS.length}`);
}

for (const cardId of STARTER_DECK_CARD_IDS) {
  if (!CARD_BY_ID[cardId]) {
    throw new Error(`Starter deck references unknown card id: ${cardId}`);
  }
}
